### ISSUE TITLE
Browse/Now Playing/Queue Navigation bar covered by Android navigation bar

### ISSUE THREAD

**Issue by byles** [CDrummond/lms-material-app#23] opened 2024-08-04 09:18 UTC
The on-screen Android navigation bar covers the Lyrion navigation bar. 

Appears app not compensating for height of on-screen three button navigation bar (edit: the app navigation doesn't appear at all when system navigation is set to gesture mode).

![Screenshot_20240804-100052](https://github.com/user-attachments/assets/eddf3941-7219-44cc-8eac-884d90408979)

moto g(10) Android 11

**Comment by CDrummond** [comment] 2024-08-04 09:42
Hmmm... This _does_ work for me on a S22 with Android14. Looking at your screenshot it appears as if the issue is because the page is _not_ rendered under the notification area - which it should be. The view should take the whole screen. Instead the WebView on your device is starting at the bottom of the notification area - as you can see by the empty space above "Living room"

Perhaps this is an Android version issue. I'll have to create a Android11 virtual device and see if I can recreate this.

**Comment by CDrummond** [comment] 2024-08-04 20:01
Should be fixed in 0.6.1

**Closed by CDrummond** 2024-08-04 20:01 UTC

**Comment by byles** [comment] 2024-08-04 20:29
Absolute legend. It goes a bit funny at smaller scale/zoom level, but I've just put it up a notch and it's perfect.
